# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-10 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworldprocess',
            name='is_draft_submit',
            field=models.BooleanField(default=False),
        ),
    ]
