# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_helloworldprocess_is_draft_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helloworldprocess',
            name='is_draft_submit',
        ),
        migrations.AddField(
            model_name='helloworldprocess',
            name='is_terminate',
            field=models.BooleanField(default=False, verbose_name='是否终止'),
        ),
    ]
